News.Web/Areas/Admin/Controllers/AdvertiseController.cs
using Microsoft.AspNetCore.Mvc;
using News.Application.Services.Implementations;
using News.Application.Services.Interfaces;
using News.Domain.ViewModels.Advertises;
using News.Domain.ViewModels.Hashtags;

namespace News.Web.Areas.Admin.Controllers
{
    public class AdvertiseController : AdminBaseController
    {
        #region Consractor

        private readonly IAdvertiseService _advertiseService;

        public AdvertiseController(IAdvertiseService advertiseService)
        {
            _advertiseService = advertiseService;
        }

        #endregion


        #region Advertise

        #region Filter Advertise

        [HttpGet]
        public async Task<IActionResult> FilterAdvertises(FilterAdvertisesViewModel filter)
        {
            var model = await _advertiseService.GetFilterAdvertisesGroups(filter);

            return View(model);
        }

        #endregion

        #region Create Advertise

        [HttpGet]
        public async Task<IActionResult> CreateAdvertise()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateAdvertise(CreateAdvertiseViewModel hashatg)
        {
            if (!ModelState.IsValid)
            {
                return View(hashatg);
            }

            var result = await _advertiseService.CreateAdvertiseGroup(hashatg);

            switch (result)
            {
                case CreateAdvertiseResult.created:
                    TempData[SuccessMessage] = " تبلیغ جدید ساخته شد";
                    return RedirectToAction("FilterAdvertises");
                case CreateAdvertiseResult.error:
                    TempData[ErrorMessage] = "خطای رخ داده است";
                    break;
            }

            return View(hashatg);
        }

        #endregion

        #region Edit Advertise

        [HttpGet]
        public async Task<IActionResult> EditAdvertise(long advertiseId)
        {
            var model = await _advertiseService.GetAdvertiseForEdit(advertiseId);

            if (model == null)
            {
                return NotFound();
            }

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> EditAdvertise(EditAdvertiseViewModel edit)
        {
            if (!ModelState.IsValid)
            {
                return View(edit);
            }

            var result = await _advertiseService.EditAdvertise(edit);

            switch (result)
            {
                case EditAdvertiseResult.success:
                    TempData[SuccessMessage] = " تبلیغ جدید ویرایش شد";
                    return RedirectToAction("FilterHashtags");
                case EditAdvertiseResult.NotFound:
                    TempData[ErrorMessage] = "تبلیغ مورد نظر یافت نشد";
                    break;
            }

            return View(edit);
        }

        #endregion

        #region Details Advertise

        [HttpGet]
        public async Task<IActionResult> DetailsAdvertise(long advertiseId)
        {
            var model = await _advertiseService.DetailsAdvertise(advertiseId);

            if (model == null)
            {
                return NotFound();
            }

            return View(model);
        }

        #endregion

        #region Delete Advertise

        [HttpPost]
        public async Task<IActionResult> DeleteAdvertise(long Id)
        {
            var result = await _advertiseService.DeleteAdvertise(Id);

            if (!result)
            {
                return new JsonResult(new { status = "error", message = "مقادیر ورودی معتبر نمی باشد." });
            }

            return new JsonResult(new { status = "success", message = "عملیات با موفقیت انجام شد." });
        }

        #endregion

        #endregion
    }
}

News.Web/Areas/Admin/Views/Advertise/CreateAdvertise.cshtml
@using News.Domain.ViewModels.Advertises
@model CreateAdvertiseViewModel

@{
    ViewData["Title"] = "ساخت تبلیغ";
}

<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            <div class="header">
                <h2>
                    @ViewData["Title"]
                </h2>
            </div>
            <div class="body">
                <form asp-area="Admin" asp-controller="Advertise" asp-action="CreateAdvertise" method="post">
                    <div class="row clearfix">
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-6">
                            <div class="form-group">
                                <div class="form-line">
                                    <label asp-for="AdsName" class="control-label"></label>
                                    <input asp-for="AdsName" class="form-control" />
                                    <span asp-validation-for="AdsName" class="text-danger"></span>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-6">
                            <div class="form-group">
                                <div class="form-line">
                                    <label asp-for="Email" class="control-label"></label>
                                    <input asp-for="Email" class="form-control" />
                                    <span asp-validation-for="Email" class="text-danger"></span>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-6">
                            <div class="form-group">
                                <div class="form-line">
                                    <label asp-for="PhoneNumber" class="control-label"></label>
                                    <input asp-for="PhoneNumber" class="form-control" />
                                    <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-6">
                            <div class="form-group">
                                <div class="form-line">
                                    <label asp-for="Subject" class="control-label"></label>
                                    <input asp-for="Subject" class="form-control" />
                                    <span asp-validation-for="Subject" class="text-danger"></span>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-6">
                            <div class="form-group">
                                <div class="form-line">
                                    <label asp-for="price" class="control-label"></label>
                                    <input asp-for="price" class="form-control" />
                                    <span asp-validation-for="price" class="text-danger"></span>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-12 col-xs-6">
                            <div class="form-group">
                                <div class="form-line">
                                    <input type="file" asp-for="AvatarImage" id="Avatar" class="form-control" placeholder="عکس اصلی">
                                    <span asp-validation-for="AvatarImage"></span>
                                </div>
                            </div>
                            <img src="" id="imgPreview" class="border my-1 mx-auto d-block" width="120px" height="120px">
                        </div>
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-6">
                            <div class="form-group">
                                <div class="form-line">
                                    <label asp-for="ExpireDate" class="control-label"></label>
                                    <input asp-for="ExpireDate" class="form-control" />
                                    <span asp-validation-for="ExpireDate" class="text-danger"></span>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                            <button type="submit" class="btn btn-success btn-lg m-l-15 waves-effect">ثبت</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts
{
    <partial name="_ValidationScripts" />

    <script>
        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    $('#imgPreview').attr('src', e.target.result);
                }

                reader.readAsDataURL(input.files[0]); // convert to base64 string
            }
        }
        $("#Avatar").change(function () {
            readURL(this);
        });
    </script>
}

News.Web/Areas/Admin/Views/Advertise/DetailsAdvertise.cshtml
@using News.Application.Statics
@using News.Domain.ViewModels.Advertises
@model DetailsAdvertiseViewModel

@{
    ViewData["Title"] = "جزیات تبلیغ";
}

<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            <div class="body">
                <div class="block-header">
                    <div class="row">
                        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                            <ul class="breadcrumb breadcrumb-style ">
                                <li class="bcrumb-1">
                                    <a href="/">خانه</a>
                                </li>
                                <li class="bcrumb-3">
                                    @ViewData["Title"]
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="card-body ">
                    <div class="product-store">
                        <div class="row">
                            <div class="col-xl-6 col-lg-6 col-md-12 col-sm-12">
                                <div class="product-gallery">
                                    <div class="product-gallery-featured">
                                        <img src="@(SiteTools.AdsImagesName + Model.Image)" alt="@Model.AdsName">
                                    </div>
                                </div>
                            </div>
                            <div class="col-xl-6 col-lg-6 col-md-12 col-sm-12">
                                <div class="product-payment-details">
                                    <h2 class="product-price display-4">@Model.AdsName</h2>
                                    <h2 class="product-price display-4">@Model.Email</h2>
                                    <h2 class="product-price display-4">@Model.PhoneNumber</h2>
                                    <h2 class="product-price display-4">@Model.price</h2>
                                    <h2 class="product-price display-4">@Model.Subject</h2>
                                    <h2 class="product-price display-4">@Model.ExpireDate</h2>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

News.Web/Areas/Admin/Views/Advertise/EditAdvertise.cshtml
@using News.Domain.ViewModels.Advertises
@model EditAdvertiseViewModel

@{
    ViewData["Title"] = "ویرایش تبلیغ";
}

<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            <div class="header">
                <h2>
                    @ViewData["Title"]
                </h2>
            </div>
            <div class="body">
                <form asp-area="Admin" asp-controller="Advertise" asp-action="EditAdvertise" method="post">
                    <div class="row clearfix">
                        <input type="hidden" asp-for="AdvertiseId" />
                        <input type="hidden" asp-for="Image" />
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-6">
                            <div class="form-group">
                                <div class="form-line">
                                    <label asp-for="AdsName" class="control-label"></label>
                                    <input asp-for="AdsName" class="form-control" />
                                    <span asp-validation-for="AdsName" class="text-danger"></span>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-6">
                            <div class="form-group">
                                <div class="form-line">
                                    <label asp-for="Email" class="control-label"></label>
                                    <input asp-for="Email" class="form-control" />
                                    <span asp-validation-for="Email" class="text-danger"></span>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-6">
                            <div class="form-group">
                                <div class="form-line">
                                    <label asp-for="PhoneNumber" class="control-label"></label>
                                    <input asp-for="PhoneNumber" class="form-control" />
                                    <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-6">
                            <div class="form-group">
                                <div class="form-line">
                                    <label asp-for="Subject" class="control-label"></label>
                                    <input asp-for="Subject" class="form-control" />
                                    <span asp-validation-for="Subject" class="text-danger"></span>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-6">
                            <div class="form-group">
                                <div class="form-line">
                                    <label asp-for="price" class="control-label"></label>
                                    <input asp-for="price" class="form-control" />
                                    <span asp-validation-for="price" class="text-danger"></span>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-12 col-xs-6">
                            <div class="form-group">
                                <div class="form-line">
                                    <input type="file" asp-for="AvatarImage" id="Avatar" class="form-control" placeholder="عکس اصلی">
                                    <span asp-validation-for="AvatarImage"></span>
                                </div>
                            </div>
                            <img src="" id="imgPreview" class="border my-1 mx-auto d-block" width="120px" height="120px">
                        </div>
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-6">
                            <div class="form-group">
                                <div class="form-line">
                                    <label asp-for="ExpireDate" class="control-label"></label>
                                    <input asp-for="ExpireDate" class="form-control" />
                                    <span asp-validation-for="ExpireDate" class="text-danger"></span>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                            <button type="submit" class="btn btn-success btn-lg m-l-15 waves-effect">ثبت</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts
{
    <partial name="_ValidationScripts" />

    <script>
        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    $('#imgPreview').attr('src', e.target.result);
                }

                reader.readAsDataURL(input.files[0]); // convert to base64 string
            }
        }
        $("#Avatar").change(function () {
            readURL(this);
        });
    </script>
}

News.Web/Areas/Admin/Views/Advertise/FilterAdvertises.cshtml
@using News.Domain.ViewModels.Advertises
@model FilterAdvertisesViewModel

@{
    ViewData["Title"] = "لیست  تبلیغ";
}

<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 mb-4">
        <div class="card">
            <div class="header">
                <h2>
                    فیلتر ها
                </h2>
            </div>
            <div class="body">
                <form asp-area="Admin" asp-controller="Advertise" asp-action="FilterAdvertises" method="get" id="filter-search">
                    <input type="hidden" asp-for="CurrentPage" />
                    <div class="row clearfix">
                        <div class="col-sm-12  col-md-4">
                            <div class="form-group form-float">
                                <div class="form-line">
                                    <input type="text" asp-for="AdsName" class="form-control">
                                    <label asp-for="AdsName" class="form-label"></label>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-12">
                            <button class="btn btn-success">جستجو</button>
                            @if (Context.Request.QueryString.HasValue)
                            {
                                <a asp-area="Admin" asp-controller="Advertise" asp-action="FilterAdvertises" class="btn btn-raised btn-primary btn-round waves-effect">حذف فیلتر</a>
                            }
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            <div class="header">
                <h2>
                    <strong>@ViewData["Title"]</strong>
                </h2>
            </div>
            <div class="body table-responsive">
                @if (Model.Entities != null && Model.Entities.Any())
                {
                    <table class="table table-condensed">
                        <thead>
                            <tr>
                                <th>آیدی</th>
                                <th> نام شرکت / فرد</th>
                                <th> ایمیل</th>
                                <th>شماره تماس</th>
                                <th>عملیات</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var advertise in Model.Entities)
                            {
                                <tr id="advertise-row-@advertise.Id">
                                    <th scope="row">@advertise.Id</th>
                                    <td>@advertise.AdsName</td>
                                    <td>@advertise.Email</td>
                                    <td>@advertise.PhoneNumber</td>
                                    <td>
                                        <a asp-area="Admin" asp-controller="Advertise" asp-action="DetailsAdvertise" asp-route-advertiseId="@advertise.Id" class="text-warning">
                                            <i class="fa fa-eye small"></i>
                                        </a>
                                        <a asp-area="Admin" asp-controller="Advertise" asp-action="EditAdvertise" asp-route-advertiseId="@advertise.Id" class="text-warning">
                                            <i class="fa fa-pen small"></i>
                                        </a>
                                        <a onclick="DeleteAdvertise('@advertise.Id')" class="text-warning">
                                            <i class="fa fa-trash small"></i>
                                        </a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                    <partial name="_AdminPagination" model="@Model.GetPaging()" />
                }
                else
                {
                    <div class="alert alert-info mb-0">
                        آیتمی پیدا نشد.
                    </div>
                }
            </div>
        </div>
    </div>
</div>